function out = pipeline_versions(what, arg)
%PIPELINE_VERSIONS What each pipeline id changed, and what it invalidates.
%
%   pipeline_versions('print')      % the history, newest last
%   pipeline_versions('current')    % 'v8' -- the id main.m stamps
%   pipeline_versions('ok')         % ids whose metric files are comparable with it
%   pipeline_versions('defects')    % runs an older id produced that must be redone
%   pipeline_versions('num', 'v7')  % 7 -- the ordering behind "older than"
%   V = pipeline_versions()         % the whole table
%
% main.m stamps every results/<alg>/ folder and every run_info with the current
% id, so a run can be traced to the code that produced it. That id is only a
% label until something says what it MEANS: this file is that something, and it
% is the single source of truth -- tools/verify_campaign.m reads `ok` and
% `defects` from here rather than carrying its own copy.
%
% Adding a version:
%   1. append an entry below, newest last;
%   2. bump `pipeline_id` in main.m to match (nothing else changes there);
%   3. set `schema_break` if the metric ROW changed shape -- that is what makes
%      older metric files incomparable rather than merely older;
%   4. fill `invalidates` if the change alters what a run WOULD have recorded on
%      particular problems. Those runs are then reported as STALE_DEFECT and
%      listed in <alg>_todo.csv for tools/redo_runs.m.
%
% A version with neither a schema break nor an `invalidates` entry leaves every
% existing result usable, which is the point of recording the distinction.

    if nargin < 1 || isempty(what)
        what = 'all';
    end

    V = history();

    switch lower(char(what))
        case 'all'
            out = V;

        case 'current'
            out = V(end).id;

        case 'ok'
            % Comparable with the current id: everything from the most recent
            % schema break onwards. Before that break the metric row has a
            % different width or meaning, so the files are a different dataset.
            last_break = find([V.schema_break], 1, 'last');
            if isempty(last_break)
                last_break = 1;
            end
            out = {V(last_break:end).id};

        case 'defects'
            % Flattened one row per (experiment, function) an older id got wrong.
            out = struct('experiment', {}, 'func', {}, 'fixed_in', {}, 'why', {});
            for k = 1:numel(V)
                for j = 1:numel(V(k).invalidates)
                    inv = V(k).invalidates(j);
                    out(end+1) = struct('experiment', inv.experiment, ...
                                        'func', inv.func, ...
                                        'fixed_in', V(k).id, ...
                                        'why', inv.why); %#ok<AGROW>
                end
            end

        case 'num'
            % 'v7' -> 7, the ordering behind "produced under an older id". An id
            % that does not parse sorts before every real one, so unknown code is
            % treated as older than any fix rather than passing the comparison.
            out = str2double(regexprep(char(arg), '^v', ''));
            if isnan(out)
                out = -Inf;
            end

        case 'print'
            fprintf('\npipeline history (current: %s)\n\n', V(end).id);
            for k = 1:numel(V)
                mark = ' ';
                if V(k).schema_break
                    mark = '*';
                end
                fprintf('%s %-4s %-12s %s\n', mark, V(k).id, V(k).date, V(k).summary);
                for i = 1:numel(V(k).detail)
                    fprintf('       %s\n', V(k).detail{i});
                end
                for j = 1:numel(V(k).invalidates)
                    fprintf('       REDO %s F%d under an older id\n', ...
                            V(k).invalidates(j).experiment, V(k).invalidates(j).func);
                end
                fprintf('\n');
            end
            fprintf('* = metric row changed shape; files from before it are a different dataset.\n');
            fprintf('comparable with %s: %s\n\n', V(end).id, strjoin(pipeline_versions('ok'), ', '));
            out = [];

        otherwise
            error('pipeline_versions:badArg', 'Unknown request "%s".', char(what));
    end
end

function V = history()
% Oldest first. Dates are when the change landed, not when a campaign ran.
%
% v1-v6 were reconstructed from the working notes and from git (main.m carries
% pipeline_id in three commits: none -> v2 -> v7). v3, v4 and v5 never appear in
% a commit -- they were bumped between commits while the recorder was being
% rewritten -- so their entries record what is known and say so where it is not.

    V = empty_entry();

    V(1) = entry('v1', '2026-04-13', ...
        'no marker file: everything that predates the stamping scheme', ...
        {'A folder with no marker at all is v1 by definition.'}, false, []);

    V(2) = entry('v2', '2026-07-22', ...
        'CEC2021 on the biased variant; CEC2020RW constraints folded into the search', ...
        {'CEC2021 moved to cec21_bias_shift_rot_func -- the basic variant''s optimum', ...
         'is 0 at the origin while get_global_minimum returns 100..2500.', ...
         'CEC2020RW constraints now enter the search inside calculate_fitness through', ...
         'guideline Eq.(2) v(x) with a 1e-4 equality tolerance and Eq.(6) scalarisation.'}, ...
        false, []);

    V(3) = entry('v3', '2026-07-25', ...
        'population history replaced by population METRICS over FE (26 columns + bsf)', ...
        {'record_history rewritten: raw individuals are no longer stored. The old', ...
         'recorder also captured only the run''s beginning, not start to end.'}, ...
        true, []);

    V(4) = entry('v4', '2026-08-01', ...
        'metric audit: 26 -> 32 columns (+bsf = 33); eight measured defects fixed', ...
        {'fdc size-dependent bias, distance cancellation, RW scale dominance, NaN', ...
         'poisoning, 0-vs-NaN unfilled rows, single-precision tail, the initial', ...
         'population never observed, feasibility read off the FE window.'}, ...
        true, []);

    V(5) = entry('v5', '2026-08-05', ...
        'recorder signature collapsed to one budget argument (schema unchanged)', ...
        {'Not separately documented at the time. Between the v4 audit and the v6 FE', ...
         'grid change the metric row did not change shape, so v5 files differ from v4', ...
         'only in the FE axis question v6 then settled.'}, ...
        false, []);

    V(6) = entry('v6', '2026-08-07', ...
        'FE grid re-anchored: row h is the first sample at or after h*step', ...
        {'Row T is now the state at max_fe; under v5 no algorithm ever recorded it', ...
         '(row 1000 sat at 99900). bsf also moved onto the grid. Columns unchanged,', ...
         'but v5 metric files are not comparable with v6: the time axis moved.'}, ...
        true, []);

    V(7) = entry('v7', '2026-08-07', ...
        'metric set expanded: 32 -> 44 columns (+bsf = 45 on disk)', ...
        {'Appended, never reordered, so bsf moved 33 -> 45: read columns BY NAME from', ...
         'the stored labels. New: raw objective, genotypic duplication, boundary', ...
         'occupancy, nearest-neighbour shape, elite geometry.'}, ...
        true, []);

    V(8) = entry('v8', '2026-08-11', ...
        'CEC2020RW F22: its g(:,8) branch is now decided per solution', ...
        {'cec20rw_func.m read `if beta == real(beta)` over the whole population, so', ...
         'one solution''s complex beta forced the 1e6 penalty onto every solution', ...
         'evaluated with it -- a point''s constraint value depended on the population', ...
         'size of the algorithm evaluating it. 7.8 % of random points in that box have', ...
         'a complex beta, so a population of 50 triggered it 98 % of the time.', ...
         'Metric row unchanged, so v7 stays comparable everywhere except that problem.', ...
         'The fix is commit ffeaaf2. Verified against the published file taken out of', ...
         'git and run beside it: identical at ps = 1 over 5000 points, a batch of 5000', ...
         'now equal to those points one by one, and all 57 problems byte-identical', ...
         'point by point with only F22 differing in a batch.', ...
         '', ...
         'Provenance note. The F22 runs redone on 2026-08-11 are stamped with commit', ...
         '3e20b9d or bce980e, and neither hash is reachable any more: both commits', ...
         'were rewritten the same day to drop a trailer from their MESSAGE, becoming', ...
         'ffeaaf2 and af49af2. The trees are byte-identical, so a run stamped with an', ...
         'old hash was produced by the code now at the new one:', ...
         '    3e20b9d -> ffeaaf2   (the fix)', ...
         '    bce980e -> af49af2   (this history file)', ...
         'v8 is what identifies the fixed code either way, which is the reason the id', ...
         'is stamped next to the hash and not instead of it.'}, ...
        false, ...
        struct('experiment', 'cec2020rw', 'func', 22, ...
               'why', ['RC22 g(:,8) was decided for the whole population at once, ' ...
                       'so a run''s constraint values depended on its batch']));
end

function e = entry(id, date, summary, detail, schema_break, invalidates)
    if isempty(invalidates)
        invalidates = struct('experiment', {}, 'func', {}, 'why', {});
    end
    e = struct('id', id, 'date', date, 'summary', summary, ...
               'detail', {detail}, 'schema_break', schema_break, ...
               'invalidates', invalidates);
end

function e = empty_entry()
    e = struct('id', {}, 'date', {}, 'summary', {}, 'detail', {}, ...
               'schema_break', {}, 'invalidates', {});
end
