% ----------------------------------------------------------------------- %
% Material Generation Algorithm (MGA) for unconstrained benchmark problems
% ----------------------------------------------------------------------- %
% Algorithm Parameters:
%   NCompan = 100   % Number of "components" (population of materials)
%
% Algorithm Concept:
%   - Chemistry-inspired: candidate solutions are materials built from
%     components; new materials are generated by mixing existing components
%     and by weighted (sum-to-one random weight) combinations, mimicking
%     chemical-compound formation.
%
% Reference:
% Siamak Talatahari, Mahdi Azizi, Amir H. Gandomi,
% Material Generation Algorithm: A Novel Metaheuristic Algorithm for
% Optimization of Engineering Problems,
% Processes 9 (5) (2021) 859.
% https://doi.org/10.3390/pr9050859
%
% Note: the original keeps a full BestSoFar history indexed by iteration; this
% port tracks the best-so-far with scalars (identical values) to avoid
% allocating a maxFe x dim array. The two "new component" generation lines and
% their (reference-quirk) bound handling are reproduced verbatim, so exactly
% one new material is evaluated per iteration as in the original.
% ----------------------------------------------------------------------- %
% Input: problem structure with fields:
%   - dimension: problem dimension
%   - lb: lower bounds
%   - ub: upper bounds
%   - maxFe: maximum function evaluations
%   - fhd: function handle
%   - number: function number
% Output: [best_fitness, best_solution, curve, population_history, fitness_history]
% ----------------------------------------------------------------------- %
function [best_fitness, best_solution, curve, population_history, fitness_history] = mga(problem)

    % Extract problem parameters
    Var_Number = problem.dimension;
    VarMin = problem.lb;
    VarMax = problem.ub;
    maxFE = problem.maxFe;

    NCompan = 100;

    FE = 0;
    curve = zeros(1, maxFE);
    history_size = 10000;
    sampling_interval = max(1, floor(maxFE / history_size));
    population_history = zeros(history_size, NCompan, Var_Number);
    fitness_history = zeros(history_size, NCompan);
    history_index = 1;

    %% Create initial components
    Compan.Position = unifrnd(repmat(VarMin, NCompan, 1), repmat(VarMax, NCompan, 1));
    [fit0, FE] = calculate_fitness(Compan.Position', problem, FE);
    Compan.Fun_Eval = fit0(:)';

    [bestFitnessVal, Index1] = min(Compan.Fun_Eval);
    best = Compan.Position(Index1, :);

    for eval_count = 1:min(FE, maxFE)
        curve(eval_count) = bestFitnessVal;
    end
    [population_history, fitness_history, history_index] = record_block(...
        Compan.Position, Compan.Fun_Eval, 1, min(FE, maxFE), ...
        population_history, fitness_history, history_index, sampling_interval, history_size);

    %% Main loop (one new material evaluated per iteration)
    while FE < maxFE
        % New component 1: mix a random component per dimension
        Index = NCompan .* (0:Var_Number - 1) + randperm(NCompan, Var_Number);
        CompnNew.Position(1, :) = Compan.Position(Index) + unifrnd(-1, 1) .* randn(1, Var_Number);

        % New component 2: weighted (sum-to-one) combination
        Index = randperm(NCompan, 1);
        Index2 = randperm(NCompan, Index);
        CMs = randn(Index, 1);
        CMs = CMs / sum(CMs);
        for iii = 1:length(CMs)
            CompnNew.Position(2, iii) = sum(CMs(iii) * Compan.Position(Index2(iii), :));
        end

        % Apply lower and upper bound limits (reproduced verbatim)
        CompnNew.Position = max(CompnNew.Position(1), VarMin);
        CompnNew.Position = max(CompnNew.Position(2), VarMin);
        CompnNew.Position = min(CompnNew.Position(1), VarMax);
        CompnNew.Position = min(CompnNew.Position(2), VarMax);

        % Evaluation
        CompnNew.Fun_Eval = zeros(1, size(CompnNew.Position, 1));
        for ind3 = 1:size(CompnNew.Position, 1)
            [CompnNew.Fun_Eval(ind3), FE] = calculate_fitness(CompnNew.Position(ind3, :)', problem, FE);
        end

        % Update components (keep the best NCompan)
        AllCompn.Position = [Compan.Position; CompnNew.Position];
        AllCompn.Fun_Eval = [Compan.Fun_Eval, CompnNew.Fun_Eval];
        [~, Index1] = sort(AllCompn.Fun_Eval);
        Compan.Position = AllCompn.Position(Index1(1:NCompan), :);
        Compan.Fun_Eval = AllCompn.Fun_Eval(Index1(1:NCompan));

        % Update best-so-far
        if Compan.Fun_Eval(1) < bestFitnessVal
            bestFitnessVal = Compan.Fun_Eval(1);
            best = Compan.Position(1, :);
        end

        if FE <= maxFE
            curve(FE) = bestFitnessVal;
            [population_history, fitness_history, history_index] = record_history(...
                FE, Compan.Position, Compan.Fun_Eval, population_history, fitness_history, ...
                history_index, sampling_interval, history_size);
        end
    end

    curve(min(FE, maxFE):end) = bestFitnessVal;

    best_solution = best;
    best_fitness = bestFitnessVal;
end

%% --- Record a fixed population snapshot over an FE block ---
function [pop_hist, fit_hist, hist_idx] = record_block(pop, costs, fe_from, fe_to, pop_hist, fit_hist, hist_idx, sampling_interval, history_size)
    if fe_to < fe_from, return; end
    for eval_count = fe_from:fe_to
        [pop_hist, fit_hist, hist_idx] = record_history(...
            eval_count, pop, costs, pop_hist, fit_hist, hist_idx, ...
            sampling_interval, history_size);
    end
end
